import { hashSemanticValue } from '@shapeshift-labs/frontier-lang-kernel';
import { createCssModuleEvidence } from './css-modules.js';
import { createCssDependencyGraphEvidence } from './dependency-graph.js';
import { parsePostcssSemanticRecords } from './postcss-parser-evidence.js';
import { safeMergeCssSource as safeMergeCssSourceImpl } from './semantic-merge.js';
export { createCssCascadeRuntimeProof } from './semantic-merge-cascade-runtime.js';

export function toCssAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-css.';
  const rules = [];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'entity' || node.kind === 'type') {
      rules.push({
        kind: 'rule',
        selector: `.frontier-${cssIdentifier(node.name)}`,
        declarations: (node.fields ?? []).map((field) => ({ property: `--frontier-field-${cssIdentifier(field.name)}`, value: JSON.stringify(typeName(field.type)) })),
        sourceRef: sourceRef(node, { regionIds: (node.fields ?? []).map((field) => field.id) })
      });
    }
    if (node.kind === 'capability') rules.push({
      kind: 'rule',
      selector: `[data-frontier-capability="${cssString(node.capability)}"]`,
      declarations: [{ property: '--frontier-capability', value: JSON.stringify(node.capability) }],
      sourceRef: sourceRef(node)
    });
  }
  return { kind: 'css.stylesheet', banner, rules };
}

export function renderCssAst(ast) {
  return renderCssAstWithSourceMap(ast).code;
}

export function renderCssAstWithSourceMap(ast, options = {}) {
  const lines = [`/* ${ast.banner} */`];
  const mappings = [];
  ast.rules.forEach((rule, index) => {
    const startLine = lines.length + 1;
    lines.push(`${rule.selector} {`);
    for (const declaration of rule.declarations) lines.push(`  ${declaration.property}: ${declaration.value};`);
    lines.push('}', '');
    if (rule.sourceRef?.semanticNodeId) mappings.push(sourceMapMapping(rule, index, startLine, lines.length - 1, options));
  });
  const code = `${lines.join('\n').trimEnd()}\n`;
  return { code, sourceMap: sourceMapEnvelope(ast, mappings, options) };
}

export function emitCss(document, options = {}) {
  return renderCssAst(toCssAst(document, options));
}

export function emitCssWithSourceMap(document, options = {}) {
  const ast = toCssAst(document, options);
  const result = renderCssAstWithSourceMap(ast, { sourceMapId: options.sourceMapId ?? `sourcemap_${idFragment(document.id)}_css`, ...options });
  return { ...result, ast };
}

export function parseCssSemanticSheet(sourceText, options = {}) {
  const sourceHash = options.sourceHash ?? hashSemanticValue({ kind: 'frontier.lang.css.source.v1', sourceText });
  const parsed = parsePostcssSemanticRecords(sourceText, sourceHash, options);
  const records = parsed.records;
  const cssModules = createCssModuleEvidence(records, options, sourceHash);
  const dependencyGraphEvidence = createCssDependencyGraphEvidence(records, { ...options, sourceHash, hashSemanticValue });
  const proofGaps = [
    ...parsed.proofGaps,
    ...records.flatMap((record) => record.proofGaps ?? []),
    ...(cssModules?.proofGaps ?? [])
  ];
  return {
    kind: 'frontier.lang.cssSemanticSheet',
    version: 1,
    sourcePath: options.sourcePath,
    sourceHash,
    records,
    cssModules,
    dependencyGraphEvidence,
    sheetHash: hashSemanticValue({ kind: 'frontier.lang.cssSemanticSheet.records.v1', records: records.map(hashableCssRecord), cssModuleHash: cssModules?.moduleHash, dependencyGraphHash: dependencyGraphEvidence.dependencyGraphHash }),
    summary: {
      rules: records.filter((record) => record.kind === 'rule').length,
      declarations: records.reduce((sum, record) => sum + (record.declarations?.length ?? 0), 0),
      scopedRules: records.filter((record) => record.scopes?.length).length,
      cssModuleExports: cssModules?.exports.length ?? 0,
      cssModuleCompositions: cssModules?.compositions.length ?? 0,
      icssImports: cssModules?.icssImports.length ?? 0,
      icssExports: cssModules?.icssExports.length ?? 0,
      dependencySurfaceCount: dependencyGraphEvidence.dependencySurfaceCount,
      customPropertyDefinitions: dependencyGraphEvidence.customPropertyDefinitions,
      customPropertyReferences: dependencyGraphEvidence.customPropertyReferences,
      animationNameLinks: dependencyGraphEvidence.animationNameLinks,
      keyframeDefinitions: dependencyGraphEvidence.keyframeDefinitions,
      fontFaceLinks: dependencyGraphEvidence.fontFaceLinks,
      urlAssetReferences: dependencyGraphEvidence.urlAssetReferences,
      propertyRegistrations: dependencyGraphEvidence.propertyRegistrations,
      propertyRegistrationDescriptors: dependencyGraphEvidence.propertyRegistrationDescriptors,
      pageDescriptors: dependencyGraphEvidence.pageDescriptors,
      pageMarginDescriptors: dependencyGraphEvidence.pageMarginDescriptors,
      proofGaps: proofGaps.length,
      parseErrors: parsed.parser.parseErrors.length
    },
    proofGaps,
    parser: parsed.parser
  };
}

export function createCssSemanticMergeEvidence(sourceText, options = {}) {
  const sheet = parseCssSemanticSheet(sourceText, options);
  return {
    kind: 'frontier.lang.cssSemanticMergeEvidence',
    version: 1,
    status: sheet.proofGaps.length ? 'needs-review' : 'ready',
    sourcePath: options.sourcePath,
    sourceHash: sheet.sourceHash,
    sheetHash: sheet.sheetHash,
    records: sheet.records,
    cssModules: sheet.cssModules,
    dependencyGraphEvidence: sheet.dependencyGraphEvidence,
    proofGaps: sheet.proofGaps,
    autoMergeClaim: false,
    semanticEquivalenceClaim: false,
    cssModuleGeneratedNameEquivalenceClaim: false,
    cssModuleUseSiteEquivalenceClaim: false,
    browserCascadeEquivalenceClaim: false,
    browserRenderEquivalenceClaim: false
  };
}

export function safeMergeCssSource(input = {}) {
  return safeMergeCssSourceImpl(input, { parseCssSemanticSheet, hashSemanticValue });
}

function sourceMapMapping(rule, index, startLine, endLine, options) {
  return compactRecord({
    id: `map_${idFragment(rule.sourceRef.semanticNodeId)}_${index}`,
    semanticNodeId: rule.sourceRef.semanticNodeId,
    sourceSpan: options.sourceSpansBySemanticNodeId?.[rule.sourceRef.semanticNodeId],
    generatedSpan: { path: options.targetPath, targetPath: options.targetPath, target: { language: 'css' }, generatedName: rule.selector, startLine, startColumn: 1, endLine, endColumn: 1 },
    target: { language: 'css' },
    generatedName: rule.selector,
    precision: 'rule-block',
    metadata: { semanticNodeKind: rule.sourceRef.semanticNodeKind, semanticNodeName: rule.sourceRef.semanticNodeName, regionIds: rule.sourceRef.regionIds }
  });
}

function sourceMapEnvelope(ast, mappings, options) {
  return compactRecord({ kind: 'frontier.lang.sourceMap', version: 1, id: options.sourceMapId ?? `sourcemap_${idFragment(ast.kind)}_css`, sourcePath: options.sourcePath, sourceHash: options.sourceHash, target: { language: 'css' }, targetPath: options.targetPath, semanticIndexId: options.semanticIndexId, mappings, evidence: options.evidence ?? [], metadata: { precision: 'rule-block', generatedSpanStrategy: 'css-renderer-rule-block' } });
}

function sourceRef(node, extra = {}) { return { semanticNodeId: node.id, semanticNodeKind: node.kind, semanticNodeName: node.name, ...extra }; }
function hashableCssRecord(record) { return { kind: record.kind, selectors: record.selectors, specificity: record.specificity, scopes: record.scopes, atRuleName: record.atRuleName, conditionText: record.conditionText, statementText: record.statementText, blockTextHash: record.blockText ? record.rawTextHash : undefined, declarations: record.declarations?.map((item) => ({ property: item.property, value: item.value, important: item.important })), proofGaps: record.proofGaps?.map((gap) => gap.code) }; }
function cssIdentifier(value) { return String(value ?? 'unknown').replace(/[^A-Za-z0-9_-]/g, '-').replace(/^-+/, '') || 'unknown'; }
function cssString(value) { return String(value ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }
function typeName(type) { return typeof type === 'string' ? type : type?.name ?? type?.kind ?? 'unknown'; }
function compactRecord(record) { return Object.fromEntries(Object.entries(record).filter(([, value]) => value !== undefined)); }
function idFragment(value) { return String(value ?? 'unknown').replace(/[^A-Za-z0-9_$]/g, '_').replace(/^_+/, '') || 'unknown'; }
