import { hashSemanticValue } from '@shapeshift-labs/frontier-lang-kernel';
import { createCssModuleEvidence } from './css-modules.js';
import { safeMergeCssSource as safeMergeCssSourceImpl } from './semantic-merge.js';

const ShorthandProperties = new Set(['all', 'animation', 'background', 'border', 'border-block', 'border-color', 'border-image', 'border-inline', 'border-radius', 'border-style', 'border-width', 'columns', 'flex', 'font', 'gap', 'grid', 'grid-area', 'grid-column', 'grid-row', 'inset', 'list-style', 'margin', 'offset', 'outline', 'overflow', 'padding', 'place-content', 'place-items', 'place-self', 'text-decoration', 'transition']);
const RuntimeAtRules = new Set(['keyframes', 'font-face', 'page', 'property']);
const ScopeAtRules = new Set(['media', 'supports', 'container', 'layer', 'scope']);

export function toCssAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-css.';
  const rules = [];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'entity' || node.kind === 'type') {
      rules.push({
        kind: 'rule',
        selector: `.frontier-${cssIdentifier(node.name)}`,
        declarations: (node.fields ?? []).map((field) => ({ property: `--frontier-field-${cssIdentifier(field.name)}`, value: JSON.stringify(typeName(field.type)) })),
        sourceRef: sourceRef(node, { regionIds: (node.fields ?? []).map((field) => field.id) })
      });
    }
    if (node.kind === 'capability') rules.push({
      kind: 'rule',
      selector: `[data-frontier-capability="${cssString(node.capability)}"]`,
      declarations: [{ property: '--frontier-capability', value: JSON.stringify(node.capability) }],
      sourceRef: sourceRef(node)
    });
  }
  return { kind: 'css.stylesheet', banner, rules };
}

export function renderCssAst(ast) {
  return renderCssAstWithSourceMap(ast).code;
}

export function renderCssAstWithSourceMap(ast, options = {}) {
  const lines = [`/* ${ast.banner} */`];
  const mappings = [];
  ast.rules.forEach((rule, index) => {
    const startLine = lines.length + 1;
    lines.push(`${rule.selector} {`);
    for (const declaration of rule.declarations) lines.push(`  ${declaration.property}: ${declaration.value};`);
    lines.push('}', '');
    if (rule.sourceRef?.semanticNodeId) mappings.push(sourceMapMapping(rule, index, startLine, lines.length - 1, options));
  });
  const code = `${lines.join('\n').trimEnd()}\n`;
  return { code, sourceMap: sourceMapEnvelope(ast, mappings, options) };
}

export function emitCss(document, options = {}) {
  return renderCssAst(toCssAst(document, options));
}

export function emitCssWithSourceMap(document, options = {}) {
  const ast = toCssAst(document, options);
  const result = renderCssAstWithSourceMap(ast, { sourceMapId: options.sourceMapId ?? `sourcemap_${idFragment(document.id)}_css`, ...options });
  return { ...result, ast };
}

export function parseCssSemanticSheet(sourceText, options = {}) {
  const lineStarts = computeLineStarts(sourceText);
  const sourceHash = options.sourceHash ?? hashSemanticValue({ kind: 'frontier.lang.css.source.v1', sourceText });
  const records = parseCssBlocks(sourceText, 0, sourceText.length, [], lineStarts, sourceHash, options);
  const cssModules = createCssModuleEvidence(records, options, sourceHash);
  const proofGaps = [
    ...records.flatMap((record) => record.proofGaps ?? []),
    ...(cssModules?.proofGaps ?? [])
  ];
  return {
    kind: 'frontier.lang.cssSemanticSheet',
    version: 1,
    sourcePath: options.sourcePath,
    sourceHash,
    records,
    cssModules,
    sheetHash: hashSemanticValue({ kind: 'frontier.lang.cssSemanticSheet.records.v1', records: records.map(hashableCssRecord), cssModuleHash: cssModules?.moduleHash }),
    summary: {
      rules: records.filter((record) => record.kind === 'rule').length,
      declarations: records.reduce((sum, record) => sum + (record.declarations?.length ?? 0), 0),
      scopedRules: records.filter((record) => record.scopes?.length).length,
      cssModuleExports: cssModules?.exports.length ?? 0,
      cssModuleCompositions: cssModules?.compositions.length ?? 0,
      icssImports: cssModules?.icssImports.length ?? 0,
      icssExports: cssModules?.icssExports.length ?? 0,
      proofGaps: proofGaps.length
    },
    proofGaps
  };
}

export function createCssSemanticMergeEvidence(sourceText, options = {}) {
  const sheet = parseCssSemanticSheet(sourceText, options);
  return {
    kind: 'frontier.lang.cssSemanticMergeEvidence',
    version: 1,
    status: sheet.proofGaps.length ? 'needs-review' : 'ready',
    sourcePath: options.sourcePath,
    sourceHash: sheet.sourceHash,
    sheetHash: sheet.sheetHash,
    records: sheet.records,
    cssModules: sheet.cssModules,
    proofGaps: sheet.proofGaps,
    autoMergeClaim: false,
    semanticEquivalenceClaim: false,
    cssModuleGeneratedNameEquivalenceClaim: false,
    cssModuleUseSiteEquivalenceClaim: false,
    browserCascadeEquivalenceClaim: false,
    browserRenderEquivalenceClaim: false
  };
}

export function safeMergeCssSource(input = {}) {
  return safeMergeCssSourceImpl(input, { parseCssSemanticSheet, hashSemanticValue });
}

function parseCssBlocks(sourceText, start, end, scopes, lineStarts, sourceHash, options) {
  const records = [];
  let index = start;
  while (index < end) {
    const open = sourceText.indexOf('{', index);
    if (open < 0 || open >= end) break;
    const close = matchingBrace(sourceText, open, end);
    if (close < 0) break;
    const preludeStart = previousBoundary(sourceText, index, open);
    const prelude = sourceText.slice(preludeStart, open).replace(/\/\*[\s\S]*?\*\//g, '').trim();
    const body = sourceText.slice(open + 1, close);
    if (prelude.startsWith('@')) {
      const at = parseAtRule(prelude, preludeStart, close + 1, lineStarts, sourceHash, scopes, options);
      records.push(at);
      if (ScopeAtRules.has(at.atRuleName)) records.push(...parseCssBlocks(sourceText, open + 1, close, [...scopes, at.scopeKey], lineStarts, sourceHash, options));
    } else if (prelude) {
      records.push(cssRuleRecord(prelude, body, preludeStart, close + 1, lineStarts, sourceHash, scopes, options));
    }
    index = close + 1;
  }
  return records;
}

function cssRuleRecord(prelude, body, start, end, lineStarts, sourceHash, scopes, options) {
  const selectors = prelude.split(',').map((selector) => selector.trim()).filter(Boolean);
  const declarations = parseDeclarations(body);
  const proofGaps = [
    ...declarations.filter((declaration) => ShorthandProperties.has(declaration.property)).map((declaration) => proofGap('css-shorthand-expansion-unproved', `CSS shorthand ${declaration.property} needs longhand expansion evidence.`)),
    ...scopes.length && !options.scopedCascadeGraphHash ? [proofGap('css-scoped-cascade-equivalence-unproved', 'Scoped cascade equivalence requires browser/style evidence.')] : []
  ];
  return compactRecord({
    kind: 'rule',
    selectors,
    selectorHash: hashSemanticValue({ kind: 'frontier.lang.css.selectors.v1', selectors }),
    specificity: selectors.map(selectorSpecificity),
    scopes,
    declarations: declarations.map((declaration, ordinal) => ({
      ...declaration,
      ordinal,
      cascadeKey: [...scopes, selectors.join(','), declaration.property].join('::'),
      declarationHash: hashSemanticValue({ kind: 'frontier.lang.css.declaration.v1', scopes, selectors, declaration })
    })),
    customProperties: declarations.filter((declaration) => declaration.property.startsWith('--')).map((declaration) => declaration.property),
    scopedCascadeGraphHash: scopes.length ? options.scopedCascadeGraphHash : undefined,
    sourceSpan: sourceSpan(start, end, lineStarts),
    sourceHash,
    ruleHash: hashSemanticValue({ kind: 'frontier.lang.css.rule.v1', selectors, scopes, declarations }),
    proofGaps: proofGaps.length ? proofGaps : undefined
  });
}

function parseAtRule(prelude, start, end, lineStarts, sourceHash, scopes, options) {
  const match = /^@([A-Za-z-]+)\s*([\s\S]*)$/.exec(prelude);
  const atRuleName = match?.[1]?.toLowerCase() ?? 'unknown';
  const conditionText = match?.[2]?.trim() ?? '';
  const proofGaps = [];
  if (RuntimeAtRules.has(atRuleName)) proofGaps.push(proofGap(`css-${atRuleName}-runtime-equivalence-unproved`, `CSS @${atRuleName} semantics require browser evidence.`));
  if (ScopeAtRules.has(atRuleName) && !options.scopedCascadeGraphHash) proofGaps.push(proofGap(`css-${atRuleName}-cascade-scope-unproved`, `CSS @${atRuleName} scoped cascade requires condition evaluation evidence.`));
  return compactRecord({
    kind: 'at-rule',
    atRuleName,
    conditionText,
    scopeKey: `@${atRuleName} ${conditionText}`.trim(),
    scopes,
    scopedCascadeGraphHash: ScopeAtRules.has(atRuleName) ? options.scopedCascadeGraphHash : undefined,
    sourceSpan: sourceSpan(start, end, lineStarts),
    sourceHash,
    atRuleHash: hashSemanticValue({ kind: 'frontier.lang.css.atRule.v1', atRuleName, conditionText, scopes }),
    proofGaps: proofGaps.length ? proofGaps : undefined
  });
}

function parseDeclarations(body) {
  return body
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split(';')
    .map((part) => part.trim())
    .filter(Boolean)
    .flatMap((part) => {
      const separator = part.indexOf(':');
      if (separator <= 0) return [];
      const rawProperty = part.slice(0, separator).trim();
      const property = rawProperty.toLowerCase();
      const value = part.slice(separator + 1).trim();
      return [{ property, rawProperty, value, important: /!important\s*$/i.test(value), valueHash: hashSemanticValue({ kind: 'frontier.lang.css.value.v1', value }) }];
    });
}

function selectorSpecificity(selector) {
  const withoutStrings = selector.replace(/"[^"]*"|'[^']*'/g, '');
  const ids = (withoutStrings.match(/#[\w-]+/g) ?? []).length;
  const classes = (withoutStrings.match(/\.[\w-]+|\[[^\]]+\]|:(?!:)[\w-]+(?:\([^)]*\))?/g) ?? []).length;
  const elements = (withoutStrings.replace(/#[\w-]+|\.[\w-]+|\[[^\]]+\]|:{1,2}[\w-]+(?:\([^)]*\))?/g, ' ').match(/\b[A-Za-z][\w-]*\b/g) ?? []).length;
  return [ids, classes, elements];
}

function matchingBrace(text, open, end) {
  let depth = 0;
  for (let index = open; index < end; index += 1) {
    if (text[index] === '{') depth += 1;
    if (text[index] === '}') {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return -1;
}

function previousBoundary(text, start, open) {
  const candidates = [text.lastIndexOf('}', open - 1), text.lastIndexOf(';', open - 1)].filter((value) => value >= start);
  return (candidates.length ? Math.max(...candidates) + 1 : start);
}

function sourceMapMapping(rule, index, startLine, endLine, options) {
  return compactRecord({
    id: `map_${idFragment(rule.sourceRef.semanticNodeId)}_${index}`,
    semanticNodeId: rule.sourceRef.semanticNodeId,
    sourceSpan: options.sourceSpansBySemanticNodeId?.[rule.sourceRef.semanticNodeId],
    generatedSpan: { path: options.targetPath, targetPath: options.targetPath, target: { language: 'css' }, generatedName: rule.selector, startLine, startColumn: 1, endLine, endColumn: 1 },
    target: { language: 'css' },
    generatedName: rule.selector,
    precision: 'rule-block',
    metadata: { semanticNodeKind: rule.sourceRef.semanticNodeKind, semanticNodeName: rule.sourceRef.semanticNodeName, regionIds: rule.sourceRef.regionIds }
  });
}

function sourceMapEnvelope(ast, mappings, options) {
  return compactRecord({ kind: 'frontier.lang.sourceMap', version: 1, id: options.sourceMapId ?? `sourcemap_${idFragment(ast.kind)}_css`, sourcePath: options.sourcePath, sourceHash: options.sourceHash, target: { language: 'css' }, targetPath: options.targetPath, semanticIndexId: options.semanticIndexId, mappings, evidence: options.evidence ?? [], metadata: { precision: 'rule-block', generatedSpanStrategy: 'css-renderer-rule-block' } });
}

function sourceSpan(start, end, lineStarts) {
  const from = positionAt(start, lineStarts);
  const to = positionAt(end, lineStarts);
  return { startOffset: start, endOffset: end, startLine: from.line, startColumn: from.column, endLine: to.line, endColumn: to.column };
}

function positionAt(offset, lineStarts) {
  let line = 0;
  while (line + 1 < lineStarts.length && lineStarts[line + 1] <= offset) line += 1;
  return { line: line + 1, column: offset - lineStarts[line] + 1 };
}

function sourceRef(node, extra = {}) { return { semanticNodeId: node.id, semanticNodeKind: node.kind, semanticNodeName: node.name, ...extra }; }
function proofGap(code, summary) { return { code, status: 'not-claimed', summary, failClosed: true, semanticEquivalenceClaim: false }; }
function hashableCssRecord(record) { return { kind: record.kind, selectors: record.selectors, specificity: record.specificity, scopes: record.scopes, atRuleName: record.atRuleName, conditionText: record.conditionText, declarations: record.declarations?.map((item) => ({ property: item.property, value: item.value, important: item.important })), proofGaps: record.proofGaps?.map((gap) => gap.code) }; }
function computeLineStarts(text) { const starts = [0]; for (let index = 0; index < text.length; index += 1) if (text[index] === '\n') starts.push(index + 1); return starts; }
function cssIdentifier(value) { return String(value ?? 'unknown').replace(/[^A-Za-z0-9_-]/g, '-').replace(/^-+/, '') || 'unknown'; }
function cssString(value) { return String(value ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }
function typeName(type) { return typeof type === 'string' ? type : type?.name ?? type?.kind ?? 'unknown'; }
function compactRecord(record) { return Object.fromEntries(Object.entries(record).filter(([, value]) => value !== undefined)); }
function idFragment(value) { return String(value ?? 'unknown').replace(/[^A-Za-z0-9_$]/g, '_').replace(/^_+/, '') || 'unknown'; }
