export interface CssScopedCascadeProof {
  readonly id?: string;
  readonly kind: 'css-scoped-cascade-proof' | 'css-source-bound-scoped-cascade-proof' | 'css-scoped-cascade-runtime-proof' | 'css-source-bound-scoped-cascade-runtime-proof' | string;
  readonly status: 'passed' | string;
  readonly proofLevel?: string;
  readonly sourcePath?: string;
  readonly reasonCode?: string;
  readonly reasonCodes?: readonly string[];
  readonly side?: 'worker' | 'head' | string;
  readonly sides?: readonly string[];
  readonly cascadeKey?: string;
  readonly cascadeKeys?: readonly string[];
  readonly ruleKey?: string;
  readonly ruleKeys?: readonly string[];
  readonly selectors?: readonly string[];
  readonly scopes?: readonly string[];
  readonly property?: string;
  readonly properties?: readonly string[];
  readonly scopedCascadeGraphShapeKey?: string;
  readonly scopedCascadeGraphShapeKeys?: readonly string[];
  readonly shapeKey?: string;
  readonly shapeKeys?: readonly string[];
  readonly scopedCascadeGraphHash?: string;
  readonly graphHash?: string;
  readonly baseScopedCascadeGraphHash?: string;
  readonly workerScopedCascadeGraphHash?: string;
  readonly headScopedCascadeGraphHash?: string;
  readonly scopedCascadeGraphHashes?: Readonly<Record<string, string>>;
  readonly graphHashes?: Readonly<Record<string, string>>;
  readonly scopedCascadeGraphHashesByShapeKey?: Readonly<Record<string, string>>;
  readonly graphHashesByShapeKey?: Readonly<Record<string, string>>;
  readonly scopedCascadeGraphHashesByRoleAndShape?: Readonly<Record<string, Readonly<Record<string, string>>>>;
  readonly baseSourceText?: string; readonly workerSourceText?: string; readonly headSourceText?: string; readonly outputSourceText?: string; readonly mergedSourceText?: string;
  readonly baseSourceHash?: string; readonly workerSourceHash?: string; readonly headSourceHash?: string; readonly outputSourceHash?: string; readonly mergedSourceHash?: string;
  readonly sourceTexts?: Readonly<Record<string, string>>;
  readonly sources?: Readonly<Record<string, string>>;
  readonly sourceHashes?: Readonly<Record<string, string>>;
  readonly hashes?: Readonly<Record<string, string>>;
}

export interface CssScopedCascadeProofRecord {
  readonly id?: string;
  readonly kind: string;
  readonly status: 'passed';
  readonly proofLevel: string;
  readonly reasonCode: string;
  readonly side: string;
  readonly cascadeKey: string;
  readonly ruleKey?: string;
  readonly property?: string;
  readonly scopes?: readonly string[];
  readonly scopedCascadeGraphShapeKey?: string;
  readonly sourcePath?: string;
  readonly scopedCascadeGraphHash?: string;
  readonly scopedCascadeGraphHashes?: Readonly<Record<string, string>>;
  readonly scopedCascadeGraphShapeKeys?: Readonly<Record<string, string>>;
  readonly baseSourceHash?: string;
  readonly workerSourceHash?: string;
  readonly headSourceHash?: string;
  readonly outputSourceHash?: string;
}
